# Generated by Django 6.0.1 on 2026-01-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='plats/')),
                ('categorie', models.CharField(choices=[('TRAD', 'Traditionnel'), ('INTL', 'International')], max_length=4)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
